name: Deploy # Actions 显示的名字，随意设置

on: [push] # 监听到 push 事件后触发

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: master # 拉取当前执行 Actions 仓库的指定分支
              uses: actions/checkout@v2
              with:
                  ref: master
            - name: Setup Node # 安装 Node 环境
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
            - name: Cache node modules
              # 设置包缓存目录，避免每次下载
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: Hexo Generate # 安装 Hexo 依赖并且生成静态文件
              run: |
                  npm i
                  npx hexo g

            - name: Hexo Deploy # 部署步骤，这里以 hexo deploy 为例
              env:
                  SSH_PRIVATE: ${{ secrets.HEXO_DEPLOY }}
                  GIT_NAME: jing-jiu
                  GIT_EMAIL: 1482877448@qq.com
                  GITHUB_REPO: github.com/jing-jiu/jing-jiu
              run: |
                  cd ./public && git init && git add .
                  git config user.name "jing-jiu"
                  git config user.email "1482877448@qq.com"
                  touch README
                  git add .
                  git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
                  git push --force --quiet "https://${{ secrets.HEXO_DEPLOY }}@$GITHUB_REPO" blog:blog
